export default {
    "nav_catalog": "nav_catalog",
    "step_catalog": "step_catalog",
    "catalog_url": "catalog_url",
    "catalog_url_missing": "catalog_url_missing",
    "catalog_url_invalid": "catalog_url_invalid",
    "hint_catalog_url": "hint_catalog_url",
    "catalog_title": "catalog_title",
    "hint_catalog_title": "hint_catalog_title",
    "catalog_title_invalid": "catalog_title_invalid",
    "catalog_type": "catalog_type",
    "hint_catalog_contact_point_name": "hint_catalog_contact_point_name",
    "catalog_contact_point_email": "catalog_contact_point_email",
    "catalog_hint_contact_point_email": "catalog_hint_contact_point_email",
    "contact_contact_point_email_missing": "contact_contact_point_email_missing",
    "contact_contact_point_email_invalid": "contact_contact_point_email_invalid",
    "help_catalog_url": "help_catalog_url",
    "help_catalog_title": "help_catalog_title",
    "help_catalog_type": "help_catalog_type",
    "help_catalog_contact_point_name": "help_catalog_contact_point_name",
    "help_catalog_contact_point_email": "help_catalog_contact_point_email",
    "catalog_summary_error": "catalog_summary_error",
    "catalog_summary_download": "catalog_summary_download",
};